<a href="https://colab.research.google.com/github/donoftime2018/Mental-Health-Chatbot/blob/generateText/NLP_DialoGPT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from transformers import pipeline, AutoTokenizer, AutoModelForCausalLM, TrainingArguments, Trainer
import pandas as pd
from datasets import Dataset
from sklearn.model_selection import train_test_split
import torch

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:
print(torch.cuda.is_available())
print(torch.cuda.get_device_name(0))

True
Tesla T4

In [4]:
device = torch.device("cuda")
device

device(type='cuda')

In [5]:
tokenizer = AutoTokenizer.from_pretrained("microsoft/DialoGPT-small", torch_dtype=torch.float32)
tokenizer.pad_token = tokenizer.eos_token
tokenizer

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:93: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
`torch_dtype` is deprecated! Use `dtype` instead!

GPT2Tokenizer(name_or_path='microsoft/DialoGPT-small', vocab_size=50257, model_max_length=1024, padding_side='right', truncation_side='right', special_tokens={'bos_token': '<|endoftext|>', 'eos_token': '<|endoftext|>', 'unk_token': '<|endoftext|>', 'pad_token': '<|endoftext|>'}, added_tokens_decoder={
	50256: AddedToken("<|endoftext|>", rstrip=False, lstrip=False, single_word=False, normalized=True, special=True),
}
)

In [6]:
model = AutoModelForCausalLM.from_pretrained("microsoft/DialoGPT-small",torch_dtype=torch.float32)
model

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

model.safetensors:   0%|          | 0.00/351M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/149 [00:00<?, ?it/s]

The tied weights mapping and config for this model specifies to tie transformer.wte.weight to lm_head.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning
GPT2LMHeadModel LOAD REPORT from: microsoft/DialoGPT-small
Key                              | Status     |  |
---------------------------------+------------+--+-
transformer.h.{0...11}.attn.bias | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

GPT2LMHeadModel(
  (transformer): GPT2Model(
    (wte): Embedding(50257, 768)
    (wpe): Embedding(1024, 768)
    (drop): Dropout(p=0.1, inplace=False)
    (h): ModuleList(
      (0-11): 12 x GPT2Block(
        (ln_1): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        (attn): GPT2Attention(
          (c_attn): Conv1D(nf=2304, nx=768)
          (c_proj): Conv1D(nf=768, nx=768)
          (attn_dropout): Dropout(p=0.1, inplace=False)
          (resid_dropout): Dropout(p=0.1, inplace=False)
        )
        (ln_2): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        (mlp): GPT2MLP(
          (c_fc): Conv1D(nf=3072, nx=768)
          (c_proj): Conv1D(nf=768, nx=3072)
          (act): NewGELUActivation()
          (dropout): Dropout(p=0.1, inplace=False)
        )
      )
    )
    (ln_f): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
  )
  (lm_head): Linear(in_features=768, out_features=50257, bias=False)
)

In [7]:
model.to(device)

GPT2LMHeadModel(
  (transformer): GPT2Model(
    (wte): Embedding(50257, 768)
    (wpe): Embedding(1024, 768)
    (drop): Dropout(p=0.1, inplace=False)
    (h): ModuleList(
      (0-11): 12 x GPT2Block(
        (ln_1): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        (attn): GPT2Attention(
          (c_attn): Conv1D(nf=2304, nx=768)
          (c_proj): Conv1D(nf=768, nx=768)
          (attn_dropout): Dropout(p=0.1, inplace=False)
          (resid_dropout): Dropout(p=0.1, inplace=False)
        )
        (ln_2): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        (mlp): GPT2MLP(
          (c_fc): Conv1D(nf=3072, nx=768)
          (c_proj): Conv1D(nf=768, nx=3072)
          (act): NewGELUActivation()
          (dropout): Dropout(p=0.1, inplace=False)
        )
      )
    )
    (ln_f): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
  )
  (lm_head): Linear(in_features=768, out_features=50257, bias=False)
)

In [8]:
dataset = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/normalized_context_and_response.csv")
dataset.head()

,context,response
0,i'm going through some things with my feelings...,if everyone thinks you're worthless then maybe...
1,i'm going through some things with my feelings...,hello and thank you for your question and seek...
2,i'm going through some things with my feelings...,first thing i'd suggest is getting the sleep y...
3,i'm going through some things with my feelings...,therapy is essential for those that are feelin...
4,i'm going through some things with my feelings...,i first want to let you know that you are not ...

In [9]:
contexts = dataset['context'].astype('str').values
contexts[:5]

array(["i'm going through some things with my feelings and myself i barely sleep and i do nothing but think about how i'm worthless and how i shouldn't be here\r\n   i've never tried or contemplated suicide i've always wanted to fix my issues but i never get around to it\r\n   how can i change my feeling of being worthless to everyone",
       "i'm going through some things with my feelings and myself i barely sleep and i do nothing but think about how i'm worthless and how i shouldn't be here\r\n   i've never tried or contemplated suicide i've always wanted to fix my issues but i never get around to it\r\n   how can i change my feeling of being worthless to everyone",
       "i'm going through some things with my feelings and myself i barely sleep and i do nothing but think about how i'm worthless and how i shouldn't be here\r\n   i've never tried or contemplated suicide i've always wanted to fix my issues but i never get around to it\r\n   how can i change my feeling of being worthless to everyone",
       "i'm going through some things with my feelings and myself i barely sleep and i do nothing but think about how i'm worthless and how i shouldn't be here\r\n   i've never tried or contemplated suicide i've always wanted to fix my issues but i never get around to it\r\n   how can i change my feeling of being worthless to everyone",
       "i'm going through some things with my feelings and myself i barely sleep and i do nothing but think about how i'm worthless and how i shouldn't be here\r\n   i've never tried or contemplated suicide i've always wanted to fix my issues but i never get around to it\r\n   how can i change my feeling of being worthless to everyone"],
      dtype=object)

In [10]:
responses = dataset['response'].astype('str').values
responses[:5]

array(["if everyone thinks you're worthless then maybe you need to find new people to hang out withseriously the social context in which a person lives is a big influence in self-esteemotherwise you can go round and round trying to understand why you're not worthless then go back to the same crowd and be knocked down againthere are many inspirational messages you can find in social media \xa0maybe read some of the ones which state that no person is worthless and that everyone has a good purpose to their lifealso since our culture is so saturated with the belief that if someone doesn't feel good about themselves that this is somehow terriblebad feelings are part of living \xa0they are the motivation to remove ourselves from situations and relationships which do us more harm than goodbad feelings do feel terrible \xa0 your feeling of worthlessness may be good in the sense of motivating you to find out that you are much better than your feelings today",
       "hello and thank you for your question and seeking advice on this feelings of worthlessness is unfortunately common in fact most people if not all have felt this to some degree at some point in their life you are not alone\xa0changing our feelings is like changing our thoughts - it's hard to do our minds are so amazing that the minute you change your thought another one can be right there to take it's place without your permission another thought can just pop in there the new thought may feel worse than the last one my guess is that you have tried several things to improve this on your own even before reaching out on here people often try thinking positive thoughts debating with their thoughts or simply telling themselves that they need to snap out of it - which is also a thought that carries some self-criticism\xa0some people try a different approach and there are counselors out there that can help you with this the idea is that instead of trying to change the thoughts you change how you respond to them you learn skills that allow you to manage difficult thoughts and feelings differently so they don't have the same impact on you that they do right now for some people they actually do begin to experience less hurtful thoughts once they learn how to manage the ones they have differently acceptance and commitment therapy may be a good choice for you\xa0there is information online and even self-help books that you can use to teach you the skills that i mentioned because they are skills they require practice but many people have found great relief and an enriched life by learning them\xa0as for suicidal thoughts i am very glad to read that this has not happened to you still you should watch out for this because it can be a sign of a worsening depression if you begin to think about this it is important to reach out to a support system right away the national suicide prevention lifeline is 1-800-273-8255 the text line is 741741\xa0i hope some other colleagues will provide you more suggestions\xa0be wellrobin landwehr dbh lpcc",
       "first thing i'd suggest is getting the sleep you need or it will impact how you think and feel i'd look at finding what is going well in your life and what you can be grateful for i believe everyone has talents and wants to find their purpose in life i think you can figure it out with some help",
       'therapy is essential for those that are feeling depressed and worthless when i work with those that are experiencing concerns related to feeling of depression and issues with self esteem i generally work with my client to help build coping skills to reduce level of depression and to assist with strengthening \xa0self esteem by guiding my client with cbt practices cbt helps with gaining a better awareness of how your thought process influences your\xa0belief system and how your beliefs impact your actions and the outcome of your behaviors \xa0this process isnt easy but it helps teach an individual that we dont always have control over what happens in our lives but we can control how we interpret feel and behave cbt is good for individuals dealing with depression anxiety toxic relationships stress self esteem codependency etc',
       'i first want to let you know that you are not alone in your feelings and there is always someone there to help you can always change your feelings and change your way of thinking by being open to trying to change you can always make yourself available to learning new things or volunteering so that you can make a purpose for yourself'],
      dtype=object)

In [11]:
def combineText(example):
    return {
        "text": f"User: {example['context']} Bot: {example['response']}"
    }

In [12]:
def encode(example):
    return tokenizer(example['text'], truncation=True, padding="max_length", max_length=128)

In [13]:
def add_labels(example):
    example['labels']=example['input_ids']
    return example

In [14]:
datasets = Dataset.from_dict({
    "context": contexts,
    "response": responses
})
datasets

Dataset({
    features: ['context', 'response'],
    num_rows: 3512
})

In [15]:
datasets_split = datasets.train_test_split(test_size=0.2)
datasets_split

DatasetDict({
    train: Dataset({
        features: ['context', 'response'],
        num_rows: 2809
    })
    test: Dataset({
        features: ['context', 'response'],
        num_rows: 703
    })
})

In [16]:
trainSet = datasets_split['train']
trainSet

Dataset({
    features: ['context', 'response'],
    num_rows: 2809
})

In [17]:
testSet = datasets_split['test']
testSet

Dataset({
    features: ['context', 'response'],
    num_rows: 703
})

In [18]:
trainSet = trainSet.map(combineText)
trainSet

Map:   0%|          | 0/2809 [00:00<?, ? examples/s]

Dataset({
    features: ['context', 'response', 'text'],
    num_rows: 2809
})

In [19]:
testSet = testSet.map(combineText)
testSet

Map:   0%|          | 0/703 [00:00<?, ? examples/s]

Dataset({
    features: ['context', 'response', 'text'],
    num_rows: 703
})

In [20]:
trainSet = trainSet.map(encode, batched=True)
trainSet

Map:   0%|          | 0/2809 [00:00<?, ? examples/s]

Dataset({
    features: ['context', 'response', 'text', 'input_ids', 'attention_mask'],
    num_rows: 2809
})

In [21]:
testSet = testSet.map(encode, batched=True)
testSet

Map:   0%|          | 0/703 [00:00<?, ? examples/s]

Dataset({
    features: ['context', 'response', 'text', 'input_ids', 'attention_mask'],
    num_rows: 703
})

In [22]:
trainSet = trainSet.map(add_labels)
trainSet

Map:   0%|          | 0/2809 [00:00<?, ? examples/s]

Dataset({
    features: ['context', 'response', 'text', 'input_ids', 'attention_mask', 'labels'],
    num_rows: 2809
})

In [23]:
testSet = testSet.map(add_labels)
testSet

Map:   0%|          | 0/703 [00:00<?, ? examples/s]

Dataset({
    features: ['context', 'response', 'text', 'input_ids', 'attention_mask', 'labels'],
    num_rows: 703
})

In [24]:
print(set(trainSet[0]["labels"]))

{513, 514, 1043, 534, 2071, 25, 550, 1576, 2612, 1593, 72, 587, 588, 1101, 1613, 612, 616, 1641, 21608, 1139, 644, 3206, 651, 655, 18579, 1180, 674, 3241, 1194, 10416, 691, 12982, 41668, 714, 717, 1744, 2776, 220, 736, 749, 1265, 761, 262, 1290, 1808, 284, 287, 1312, 290, 812, 815, 3382, 1849, 318, 319, 326, 329, 339, 340, 2904, 345, 351, 867, 356, 355, 373, 2936, 892, 4988, 389, 393, 37264, 922, 11678, 1445, 422, 423, 32682, 1972, 3511, 1464, 1975, 1978, 1466, 2492, 18877, 460, 465, 466, 467, 468, 470, 475, 502, 503}

In [25]:
trainingArgs = TrainingArguments(
    output_dir="./output",
    num_train_epochs=3,
    learning_rate=2e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    eval_strategy='steps',
    warmup_steps=50,
    weight_decay=0.01,
    logging_dir=None,
    fp16=False,
    bf16=False,
    max_grad_norm = 1.0
)

In [26]:
trainSet = trainSet.select(range(1100))

In [27]:
testSet = testSet.select(range(670))

In [28]:
inputs = tokenizer.encode(
	input(">> User: ") + " Bot: " + tokenizer.eos_token, return_tensors='pt'
).to(model.device)

outputs = model.generate(input_ids=inputs, max_length=50, max_new_tokens=50,repetition_penalty=1.1,  do_sample=True, temperature=0.7, top_p=0.7, num_return_sequences=5)

>> User: I feel completely lost after my dog died. What should I do to cope day to day?

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
The attention mask is not set and cannot be inferred from input because pad token is same as eos token. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Both `max_new_tokens` (=50) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

In [29]:
tokenizer.decode(outputs, skip_special_tokens=True)

["I feel completely lost after my dog died. What should I do to cope day to day? Bot: We can't help you . We are all animals and we need comfort , not pain ! Dogma 101 by u jwcgj 42 bot is here if anyone else needs a hand with anything important today ... :D DDDd ? Thanks",
 "I feel completely lost after my dog died. What should I do to cope day to day? Bot: It's a good thing you're here . It can't get any worse , right ? ! :D DDDd ... You'll be fine though man .. Just keep going and don ' cry about it until tomorrow when we are all gone toooo",
 "I feel completely lost after my dog died. What should I do to cope day to day? Bot: Aww , that's so sweet . She was a beautiful girl ! Thanks for sharing this story with us all lt 3 It is really touching and heartwarming how much she means you too ... hugs :D D Edit spelling mistakes ? x3 s",
 "I feel completely lost after my dog died. What should I do to cope day to day? Bot: Aww , you're just a bot . Don't worry about it ! You'll be fine :D lt 3 hugs and treats are your best friend in the world btw ... for now anyway .. lolol x3 amp hearts hope everything is",
 "I feel completely lost after my dog died. What should I do to cope day to day? Bot: Aww , that's so sweet . Thank you for sharing your story ! You're a great person and this is what we needed from the internet today lt 3333 Edit : words are hard xD Thanks u pugofchickenface amp"]

In [30]:
trainer=Trainer(
    model=model,
    args=trainingArgs,
    train_dataset= trainSet,
    eval_dataset=testSet
)

In [31]:
trainer.evaluate(testSet)

`loss_type=None` was set in the config but it is unrecognized. Using the default loss: `ForCausalLMLoss`.

{'eval_loss': 8.094528198242188,
 'eval_model_preparation_time': 0.0018,
 'eval_runtime': 6.7448,
 'eval_samples_per_second': 99.336,
 'eval_steps_per_second': 6.227}

In [32]:
trainer.predict(testSet.select(range(80)))

PredictionOutput(predictions=array([[[ 25.190083,  20.328644,  19.92158 , ...,  23.659128,
          22.035858,  24.333473],
        [398.70972 , 360.67093 , 359.06384 , ..., 395.01428 ,
         398.91608 , 410.0853  ],
        [362.15216 , 326.86182 , 320.0437  , ..., 358.06866 ,
         361.63876 , 370.24478 ],
        ...,
        [419.74274 , 375.5734  , 373.1483  , ..., 414.201   ,
         419.924   , 433.83228 ],
        [420.5586  , 375.22424 , 372.34265 , ..., 412.80453 ,
         418.1659  , 433.92334 ],
        [425.9636  , 380.76953 , 377.83163 , ..., 421.52594 ,
         424.826   , 442.71872 ]],

       [[ 25.190083,  20.328644,  19.92158 , ...,  23.659128,
          22.035858,  24.333473],
        [398.70972 , 360.67093 , 359.06384 , ..., 395.01428 ,
         398.91608 , 410.0853  ],
        [362.15216 , 326.86182 , 320.0437  , ..., 358.06866 ,
         361.63876 , 370.24478 ],
        ...,
        [394.37717 , 349.94513 , 351.04865 , ..., 387.6764  ,
         392.10992 , 409.27045 ],
        [376.31342 , 334.88055 , 332.06738 , ..., 367.08865 ,
         373.08163 , 391.84113 ],
        [423.41577 , 375.26465 , 373.1583  , ..., 415.94742 ,
         417.5051  , 438.84235 ]],

       [[ 25.190083,  20.328644,  19.92158 , ...,  23.659128,
          22.035858,  24.333473],
        [398.70972 , 360.67093 , 359.06384 , ..., 395.01428 ,
         398.91608 , 410.0853  ],
        [294.9164  , 265.88736 , 263.898   , ..., 293.4246  ,
         294.85602 , 304.034   ],
        ...,
        [405.0823  , 362.50467 , 362.78357 , ..., 403.3591  ,
         407.98666 , 423.2502  ],
        [393.1457  , 352.52634 , 351.6659  , ..., 391.6157  ,
         396.08212 , 412.02322 ],
        [417.7655  , 373.77026 , 373.18814 , ..., 417.10983 ,
         419.17374 , 437.49512 ]],

       ...,

       [[ 25.190083,  20.328644,  19.92158 , ...,  23.659128,
          22.035858,  24.333473],
        [398.70972 , 360.67093 , 359.06384 , ..., 395.01428 ,
         398.91608 , 410.0853  ],
        [362.15216 , 326.86182 , 320.0437  , ..., 358.06866 ,
         361.63876 , 370.24478 ],
        ...,
        [421.31058 , 380.83398 , 375.01376 , ..., 421.9698  ,
         421.42377 , 434.87158 ],
        [425.50955 , 382.80783 , 380.25345 , ..., 421.55197 ,
         425.0028  , 440.43323 ],
        [421.0587  , 379.22086 , 375.91797 , ..., 419.11093 ,
         421.3971  , 439.4196  ]],

       [[ 25.190083,  20.328644,  19.92158 , ...,  23.659128,
          22.035858,  24.333473],
        [398.70972 , 360.67093 , 359.06384 , ..., 395.01428 ,
         398.91608 , 410.0853  ],
        [294.9164  , 265.88736 , 263.898   , ..., 293.4246  ,
         294.85602 , 304.034   ],
        ...,
        [416.9598  , 371.28256 , 370.38626 , ..., 412.798   ,
         417.81293 , 432.1091  ],
        [355.65585 , 312.1562  , 315.85934 , ..., 346.26404 ,
         357.41467 , 367.24808 ],
        [419.19482 , 374.6307  , 373.27655 , ..., 414.65817 ,
         419.36166 , 438.26944 ]],

       [[ 25.190083,  20.328644,  19.92158 , ...,  23.659128,
          22.035858,  24.333473],
        [398.70972 , 360.67093 , 359.06384 , ..., 395.01428 ,
         398.91608 , 410.0853  ],
        [385.19913 , 348.31595 , 338.6069  , ..., 377.0732  ,
         383.9948  , 395.5756  ],
        ...,
        [400.31332 , 359.05756 , 357.86545 , ..., 400.63977 ,
         404.17734 , 417.68826 ],
        [401.8787  , 358.29977 , 358.07532 , ..., 400.3042  ,
         402.40427 , 420.31644 ],
        [418.93286 , 374.3167  , 373.5705  , ..., 417.82065 ,
         418.93118 , 438.53012 ]]], dtype=float32), label_ids=array([[12982,    25,  1312, ...,   345,   561,  4601],
       [12982,    25,  1312, ...,  5450,  1228,   381],
       [12982,    25,   616, ...,  4379,   257,  1957],
       ...,
       [12982,    25,  1312, ...,  1862,  1048,   284],
       [12982,    25,   616, ...,  1048,   220,  1849],
       [12982,    25,  2158, ...,   655,   530,   286]]), metrics={'test_loss': 8.022115707397461, 'test_model_preparation_time': 0.0018, 'test_runtime': 2.6486, 'test_samples_per_second': 30.205, 'test_steps_per_second': 1.888})

In [33]:
trainer.train()

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

TrainOutput(global_step=207, training_loss=4.5105349038534115, metrics={'train_runtime': 130.4311, 'train_samples_per_second': 25.301, 'train_steps_per_second': 1.587, 'total_flos': 313387116134400.0, 'train_loss': 4.5105349038534115, 'epoch': 3.0})

In [34]:
trainer.save_model("/content/drive/MyDrive/Colab Notebooks/mental-health-dialogpt")

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

In [35]:
trainer.evaluate(testSet)

{'eval_loss': 3.3855626583099365,
 'eval_model_preparation_time': 0.0018,
 'eval_runtime': 7.3954,
 'eval_samples_per_second': 90.597,
 'eval_steps_per_second': 5.679,
 'epoch': 3.0}

In [36]:
trainer.predict(testSet.select(range(80)))

PredictionOutput(predictions=array([[[ 25.49744 ,  20.585709,  20.078077, ...,  23.11365 ,
          21.715027,  24.730785],
        [143.63153 , 134.07947 , 131.4706  , ..., 141.99893 ,
         143.26863 , 153.42424 ],
        [178.1252  , 167.42719 , 163.74484 , ..., 177.11588 ,
         184.19087 , 188.56958 ],
        ...,
        [100.10247 ,  96.0638  ,  93.253914, ...,  99.35485 ,
         107.92419 , 106.86241 ],
        [ 85.022934,  81.223076,  77.64591 , ...,  82.76014 ,
          87.59554 ,  90.368805],
        [227.26001 , 202.92079 , 201.36984 , ..., 217.51129 ,
         221.86655 , 247.11723 ]],

       [[ 25.49744 ,  20.585709,  20.078077, ...,  23.11365 ,
          21.715027,  24.730785],
        [143.63153 , 134.07947 , 131.4706  , ..., 141.99893 ,
         143.26863 , 153.42424 ],
        [178.1252  , 167.42719 , 163.74484 , ..., 177.11588 ,
         184.19087 , 188.56958 ],
        ...,
        [ 88.633606,  80.75555 ,  82.13293 , ...,  79.29682 ,
          82.96341 ,  97.32585 ],
        [133.15169 , 118.99229 , 115.90219 , ..., 120.094185,
         127.23749 , 138.84006 ],
        [286.49286 , 256.61557 , 255.19307 , ..., 275.64035 ,
         278.79175 , 305.25485 ]],

       [[ 25.49744 ,  20.585709,  20.078077, ...,  23.11365 ,
          21.715027,  24.730785],
        [143.63153 , 134.07947 , 131.4706  , ..., 141.99893 ,
         143.26863 , 153.42424 ],
        [105.96591 , 101.07152 ,  97.42555 , ..., 110.12942 ,
         110.3348  , 113.54089 ],
        ...,
        [148.53314 , 138.73245 , 137.09949 , ..., 148.33641 ,
         148.1568  , 158.30557 ],
        [108.538506, 103.41528 , 100.11347 , ..., 104.71346 ,
         110.112335, 116.508224],
        [292.2457  , 263.11823 , 262.20557 , ..., 285.03882 ,
         287.41095 , 314.1956  ]],

       ...,

       [[ 25.49744 ,  20.585709,  20.078077, ...,  23.11365 ,
          21.715027,  24.730785],
        [143.63153 , 134.07947 , 131.4706  , ..., 141.99893 ,
         143.26863 , 153.42424 ],
        [178.1252  , 167.42719 , 163.74484 , ..., 177.11588 ,
         184.19087 , 188.56958 ],
        ...,
        [ 66.832825,  65.47817 ,  62.11231 , ...,  67.16013 ,
          68.429276,  74.35519 ],
        [ 59.367054,  55.5237  ,  54.255222, ...,  56.89219 ,
          59.688858,  68.45047 ],
        [135.70064 , 122.61314 , 121.68175 , ..., 130.68059 ,
         132.5775  , 154.16103 ]],

       [[ 25.49744 ,  20.585709,  20.078077, ...,  23.11365 ,
          21.715027,  24.730785],
        [143.63153 , 134.07947 , 131.4706  , ..., 141.99893 ,
         143.26863 , 153.42424 ],
        [105.96591 , 101.07152 ,  97.42555 , ..., 110.12942 ,
         110.3348  , 113.54089 ],
        ...,
        [ 64.865524,  61.00808 ,  57.93231 , ...,  61.86527 ,
          64.39471 ,  74.58236 ],
        [ 16.778027,  14.517955,  15.182144, ...,  10.73684 ,
          16.977938,  24.073254],
        [239.972   , 217.60776 , 216.58733 , ..., 233.06255 ,
         237.4114  , 261.76724 ]],

       [[ 25.49744 ,  20.585709,  20.078077, ...,  23.11365 ,
          21.715027,  24.730785],
        [143.63153 , 134.07947 , 131.4706  , ..., 141.99893 ,
         143.26863 , 153.42424 ],
        [147.6261  , 137.36084 , 133.2263  , ..., 146.60153 ,
         149.23685 , 156.43323 ],
        ...,
        [111.58949 , 105.628525, 102.87912 , ..., 114.23925 ,
         116.38437 , 120.77088 ],
        [100.50895 ,  95.13642 ,  91.621025, ...,  99.99125 ,
         101.92383 , 109.06418 ],
        [324.53076 , 289.98804 , 288.82214 , ..., 314.22745 ,
         317.3055  , 345.82266 ]]], dtype=float32), label_ids=array([[12982,    25,  1312, ...,   345,   561,  4601],
       [12982,    25,  1312, ...,  5450,  1228,   381],
       [12982,    25,   616, ...,  4379,   257,  1957],
       ...,
       [12982,    25,  1312, ...,  1862,  1048,   284],
       [12982,    25,   616, ...,  1048,   220,  1849],
       [12982,    25,  2158, ...,   655,   530,   286]]), metrics={'test_loss': 3.341477155685425, 'test_model_preparation_time': 0.0018, 'test_runtime': 2.3787, 'test_samples_per_second': 33.632, 'test_steps_per_second': 2.102})